backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Landing Page'
        name: 'landingpage'
        format: 'json'
        file: 'content/pages/landingpage.json'
        fields:
          - {
              label: 'Services',
              name: 'services',
              widget: 'list',
              fields:
                [
                  { label: 'Service', name: 'service', widget: 'string' },
                  { name: 'image', label: 'Image', widget: 'image' },
                ],
            }
          - {
              label: 'Bios',
              name: 'bios',
              widget: 'list',
              fields:
                [
                  { name: 'name', label: 'Name', widget: 'string' },
                  {
                    name: 'credentials',
                    label: 'Credentials',
                    widget: 'string',
                  },
                  { name: 'headshot', label: 'Head Shot', widget: 'image' },
                  { name: 'bio', label: 'Bio', widget: 'text' },
                ],
            }
          - {
              label: 'Testimonials',
              name: 'testimonials',
              widget: 'list',
              fields:
                [
                  { name: 'name', label: 'Name', widget: 'string' },
                  { name: 'testimonial', label: 'Testimonial', widget: 'text' },
                ],
            }
          - { label: 'Mission Statement', name: 'mission', widget: 'text' }
