backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Landing Page'
        name: 'landingpage'
        format: 'json'
        file: 'content/pages/landingpage.json'
        fields:
          - {
              label: 'Services',
              name: 'services',
              widget: 'list',
              field: { label: 'Service', name: 'service', widget: 'string' },
            }
