backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'bios'
    label: 'Bios'
    format: 'json'
    folder: 'content/bios'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'string' }
      - { label: 'Headshot', name: 'headshot', widget: 'image' }
