backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    format: 'json'
    files:
      - label: 'Landing Page'
        name: 'landingpage'
        file: 'content/pages/landingpage.json'
        fields:
          - {
              label: 'Services',
              name: 'services',
              widget: 'list',
              field: 'string',
            }
