backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    format: 'json'
    files:
      - label: 'Landing Page'
        name: 'landingpage'
        file: 'content/pages/landingpage.json'
        fields:
          - label: 'Bios'
            name: 'bios'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Bio', name: 'bio', widget: 'string' }
              - { label: 'Headshot', name: 'headshot', widget: 'image' }
          - label: 'Services'
            name: 'services'
            widget: 'list'
            field: 'string'
